# Generated by Django 4.1.2 on 2023-09-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_item_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
