# Generated by Django 4.1.2 on 2023-09-08 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0005_item_transaction_status_alter_category_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
