# Generated by Django 4.1.2 on 2023-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_item_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='transaction_status',
            field=models.CharField(choices=[('Listed', 'Listed'), ('Sold', 'Sold')], default='Listed', max_length=10),
        ),
    ]
