# Generated by Django 4.1.2 on 2023-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='transaction',
            field=models.IntegerField(default=0),
        ),
    ]
